### ISSUE TITLE
JUnitTest Error

### ISSUE THREAD

**Issue by 160731liupf** [apache/servicecomb-fence#18]
When I run the test by url: http://localhost:9093/v1/test/start,it throws Exception:"JWT must have 3 tokens".

**Comment by liubao68** [comment]
Does the test returns success and "JWT must have 3 tokens" only in logs, or the tests result shows not success?

**Comment by liubao68** [comment]
This is a bug, the latest PR introduces this error, I 'll fix it.

**Comment by liubao68** [comment]
I create a [PR](https://github.com/apache/servicecomb-fence/pull/19)  for this

**Comment by 160731liupf** [comment]
Thanks a lot,I will synchronize this PR later.
