### ISSUE TITLE
EdgeService, Authentication, Authorization(ResourceServer)独立运行会不会有性能问题？

### ISSUE THREAD

**Issue by loringao** [apache/servicecomb-fence#20]
按照servicecomb-fence的示例，EdgeService, Authentication, Authorization(ResourceServer) 是独立的微服务，会不会有性能问题？如果整合的化是否合理?

**Comment by liubao68** [comment]
里面的edge service是示例，其实也可以不存在的。不过推荐的微服务架构下都会包含edge service，这是一种弹性的架构，fence开发的时候，充分考虑了edge service的水平扩容。 我有个[文章](https://bbs.huaweicloud.com/blogs/101611)分析了这个问题，供参考。

**Comment by loringao** [comment]
谢谢！
