### ISSUE TITLE
servicecomb-fence鉴权是集中鉴权还是分布式鉴权？

### ISSUE THREAD

**Issue by loringao** [apache/servicecomb-fence#21]
按照servicecomb-fence 作者的[博客](https://zhuanlan.zhihu.com/p/77366884) 描述：验证的行为是由 business-service来完成的，感觉与fence的的 ResourceServer实现的鉴权方式有些不一致，
 
我的理解(在只有一个token简化的场景下，没有access token，id token的转换情况下)：
1. ui ->edgeservice->authenticate->token, 
2.ui-withtoken->edgeservie->business-service(verify token)
  
看官方代码好像是：
2.ui-withtoken->edgeservie-> resourceserver（verify token） ->business-service
   
我的疑惑是：
1. 微服务内部调用（不走edgeservice，只走注册中心）鉴权是通过自行验证还是通过ResourceServer独立验证？

2. ResourceServer是管理所有的鉴权还是各个微服务实现自己的ResourceServer自行鉴权？

**Comment by liubao68** [comment]
这个项目中的"ResourceServer"其实就是你说的"business-service"，即业务的每一个微服务都是ResourceServer，这样理解就和文章中的“分布式鉴权”对应起来了，分布式的意思就是鉴权过程发生在每个微服务里面，每个微服务自己定义哪些操作能够被哪些角色访问，而不需要再去访问集中的权限管理服务实现鉴权。 resource server是OAuth的叫法。

**Comment by loringao** [comment]
理解了，非常感谢。
